Repository zenml-io/blog.zenml.io, pull requests merged in 2022-11, with the labels that each got.

#121 Update gh actions blog
  _posts/2022-06-20-github-actions-orchestrator.md
Labels: internal

#108 Fix broken links
  .github/teams.yml
  .github/workflows/markdown-link-check.yml
  .github/workflows/markdown_check_config.json
  _posts/2020-02-27-distributed_pca.md
  _posts/2020-04-01-deep_learning_33_million_with_few_lines_yaml.md
  _posts/2020-05-01-predicting_the_winner_of_a_dota_2_match.md
  _posts/2020-06-06-technical_debt.md
  _posts/2020-06-11-can_you_do_the_splits.md
  _posts/2020-06-26-ml_in_production_is_still_broken.md
  _posts/2021-10-27-ml-pipeline-challenge.md
  _posts/2021-11-16-release_0_5_x.md
  _posts/2021-11-24-zero-five-three-release.md
  _posts/2021-12-03-zero-five-four-release.md
  _posts/2021-12-06-caching-ml-pipelines.md
  _posts/2021-12-13-zero-five-five-release.md
  _posts/2021-12-14-why-zenml.md
  _posts/2021-12-23-zero-five-six-release.md
  _posts/2022-01-06-examples-cli.md
  _posts/2022-01-17-zero-five-seven-release.md
  _posts/2022-01-21-zenml-loves-evidently.md
  _posts/2022-01-26-mypy-typing.md
  _posts/2022-01-26-zero-six-zero-release.md
  _posts/2022-02-07-zero-six-one-release.md
  _posts/2022-02-23-zero-six-two-release.md
  _posts/2022-02-28-richify-that-cli.md
  _posts/2022-03-14-zero-six-three-release.md
  _posts/2022-03-17-solving_atari_games_with_ai.md
  _posts/2022-03-24-step-operators-training.md
  _posts/2022-03-28-zero-seven-zero-release.md
  _posts/2022-04-11-zero-seven-one-release.md
  _posts/2022-05-11-ci-ct-cd-with-zenml.md
  _posts/2022-05-18-zero-eight-zero-release.md
  _posts/2022-05-24-zenml-mlops-framework.md
  _posts/2022-05-27-customer-churn.md
  _posts/2022-06-20-github-actions-orchestrator.md
  _posts/2022-06-27-vertex-ai-blog.md
  _posts/2022-07-19-zero-eleven-zero-release.md
  _posts/2022-08-03-deploy-with-kserve.md
  _posts/2022-09-01-zero-thirteen-release.md
  _posts/2022-09-06-deepchecks-and-zenml.md
Labels: bug, documentation, enhancement, internal

#123 Remove extra backslash
  _includes/blogposts.html
Labels: bug, internal

#128 Update zenhack three pointer prediction blog post
  _posts/2022-02-02-zenhack-three-pointer-prediction.md
Labels: internal

#126 Update Vertex AI Blog post
  _posts/2022-06-27-vertex-ai-blog.md
Labels: internal

#130 update deepchecks blogpost
  _posts/2022-09-06-deepchecks-and-zenml.md
Labels: internal

#125 Update Kubernetes Blog Post
  _posts/2022-06-29-k8s-orchestrator.md
Labels: internal

#131 Update operators training blog post
  _posts/2022-03-24-step-operators-training.md
  _posts/2022-04-20-customer_satisfaction.md
  _posts/2022-06-29-k8s-orchestrator.md
Labels: internal

#133 update customer churn blog post
  _posts/2022-05-27-customer-churn.md
  assets/posts/customer-churn/aws_kubeflow_stack.png
Labels: internal

#122 PyTorch experiment tracking blog post
  _posts/2020-06-11-can_you_do_the_splits.md
  _posts/2021-11-16-release_0_5_x.md
  _posts/2022-06-10-open-source-data-annotation-tools.md
  _posts/2022-10-27-pytorch-experiment-tracking.md
  assets/posts/pytorch_wandb/dashboard-login.png
  assets/posts/pytorch_wandb/dashboard.gif
  assets/posts/pytorch_wandb/fire.gif
  assets/posts/pytorch_wandb/meme.jpg
  assets/posts/pytorch_wandb/pipeline_step.gif
  assets/posts/pytorch_wandb/pytorch_wandb.gif
  assets/posts/pytorch_wandb/pytorch_wandb.png
  assets/posts/pytorch_wandb/success.gif
  assets/posts/pytorch_wandb/thumbnail.gif
  assets/posts/pytorch_wandb/wandb_dashboard.png
Labels: internal

#124 Update mlflow blogpost
  _posts/2022-01-06-examples-cli.md
  _posts/2022-02-09-mlflow-tracking.md
Labels: bug, internal

#134 ZenML Month of MLOps Recap Blog Post
  _posts/2022-11-22-mlops-competition-recap.md
  assets/posts/competition-recap/Final.png
  assets/posts/competition-recap/Judges.png
  assets/posts/competition-recap/Poster.png
  assets/posts/competition-recap/Recap.gif
Labels: internal

#136 Minor typo and paragraph fix on competition recap blog
  _posts/2022-11-22-mlops-competition-recap.md
Labels: internal
